In [1]:
import numpy as np

In [2]:
def fit(self, X, y):

    self._new_X = X
    if self.fit_intercept == True:
        one_vector = np.ones((len(self._new_X), 1))
        self._new_X = np.concatenate( (one_vector, self._new_X), axis =1 )
    else:
        pass

    XTX = np.dot(X.T, X)
    XTX_inv = np.linalg.inv(XTX)
    theta_pred = np.dot(np.dot(XTX_inv, X.T), y)

    self._theta_pred = theta_pred
    return self

In [3]:
def predict(self, X):
    if self.fit_intercept == True:
        one_vector = np.ones((len(X), 1))
        X = np.concatenate((one_vector, X), axis = 1)
    else:
        pass

    return np.dot(X, self._theta_pred)

In [4]:
import numpy as np

class LinearRegression(object):
    def __init__(self, fit_intercept=True, copy_X=True):
        self.fit_intercept = fit_intercept
        self.copy_X = copy_X

        self._coef = None
        self._intercept = None
        self._new_X = None
        
        self._theta_pred = None

    def fit(self, X, y):

        self._new_X = X

        if self.fit_intercept == True:
            one_vector = np.ones((len(self._new_X), 1))
            self._new_X = np.concatenate( (one_vector, self._new_X), axis =1 )

        XTX = np.dot(self._new_X.T, self._new_X)
        XTX_inv = np.linalg.inv(XTX)
        theta_pred = np.dot(np.dot(XTX_inv, self._new_X.T), y)

        self._theta_pred = theta_pred
        self._intercept = self._theta_pred[0]
        self._coef = self._theta_pred[1:]
        
        return self

    def predict(self, X):
        if self.fit_intercept == True:
            one_vector = np.ones((len(X), 1))
            new_X = np.concatenate((one_vector, X), axis = 1)
        else:
            pass

        return np.dot(new_X, self._theta_pred)

    @property
    def coef(self):
        return self._coef

    @property
    def intercept(self):
        return self._intercept

In [5]:
import pandas as pd
import numpy as np
import linear_model
import imp
imp.reload(linear_model)

import warnings
warnings.filterwarnings(action='ignore')

In [6]:
df = pd.read_csv('../data/test.csv')
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [7]:
X = df['x'].values.reshape(-1,1)
y = df['y'].values

In [8]:
one_vector = np.ones((len(X), 1))
new_X = np.concatenate( (one_vector, X), axis =1 )

XTX = np.dot(new_X.T, new_X)
XTX_inv = np.linalg.inv(XTX)
theta_pred = np.dot(np.dot(XTX_inv, new_X.T), y)

theta_pred

array([-0.46181077,  1.01433536])

In [9]:
one_vector = np.ones((len(X), 1))
new_X = np.concatenate( (one_vector, X), axis =1 )

np.dot(new_X, theta_pred)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [10]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [11]:
lr.fit(X,y)

In [12]:
lr.intercept

-0.4618107736611232

In [13]:
lr.coef

array([1.01433536])