# 1. Comparisons
### 1.1 All & Any
- Array의 Data 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [16]:
import numpy as np

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Or 조건 <br>
`any` : `하나라도` 조건에 `만족`한다면 -> `True`

In [18]:
np.any(a>5), np.any(a<0)

(True, False)

- And 조건 <br>
`all` : `모두` 조건에 `만족`한다면 -> `True` <br>
하나라도 만족하지 않으면 -> False

In [19]:
np.all(a>5) , np.all(a<10)

(False, True)

### 1.2 comparison operation #1
- numpy is 배열의 size가 same 할 때 element간 비교의 결과를 Boolean type으로 반환

In [27]:
a = np.array([1,3,0], float)
b = np.array([5,2,1], float)

In [21]:
a > b

array([False,  True, False])

In [22]:
a == b

array([False, False, False])

In [28]:
a >= b

array([False,  True, False])

In [29]:
(a > b).all()

False

In [23]:
# 하나라도 True -> True
(a > b).any()

True

### 1.3 comparison operation #2

- logical_and 
: 둘 중 하나라도 False -> Flase / `둘 다 True -> True` <br>  
ex) a = np.array([1,3,0], float) <br>
np.logical_and(a>0 , a<3) <br>
1) a > 0 -> T, T, F <br>
2) a < 3 -> T, F, T <br>
=> T, F, F

In [34]:
a = np.array([1,3,0], float)
# and 조건의 condition
np.logical_and(a>0 , a<3)

array([ True, False, False])

- logical_not
: True -> False , False -> True

In [25]:
b = np.array([True, False, True], bool)
# Not 조건의 Condition
np.logical_not(b)

array([False,  True, False])

- logical_or
: `둘 중 하나라도 True -> True`

In [26]:
# OR 조건의 condition
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

### 1.4 np.where
- tuple 형태로 반환

In [35]:
# where(condition, True, False)
np.where(a>0,3,2)
# True -> 3, False -> 2

array([3, 3, 2])

In [41]:
a = np.arange(10)
# Index 값으로 반환
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

- isnan , isfinite : 어떤 조건을 찾는 것
- isnan : memory의 값이 존재하지 않는 경우, None -> True
- isfinite : 한정되지 않는 값

In [38]:
a = np.array([1, np.NaN, np.Inf], float)
# Not a Number
np.isnan(a)

array([False,  True, False])

In [40]:
# is finite number
np.isfinite(a)

array([ True, False, False])

### 1.5 argmax & argmin

- array 내 최대값 또는 최소값의 `index`를 반환

In [49]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [52]:
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [56]:
# 작은 값의 Index부터 반환
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [57]:
# 큰 값의 Index부터 반환
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

- axis 기반의 반환

In [43]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
# axis =1 : 각 행 단위에서, axis =0 : 각 열 단위에서
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

# 2. Boolean & Fanacy index
### 2.1 boolean index
- 특정 조건에 따른 값을 배열 형태로 추출
- Comparison operation 함수들도 모두 사용가능

In [58]:
a = np.array([1,4,0,2,3,8,9,7], float)
a > 3

array([False,  True, False, False, False,  True,  True,  True])

In [61]:
a.shape

(8,)

In [62]:
(a>3).shape

(8,)

In [59]:
# 조건이 True인 index의 element만 추출|
a[a>3]

array([4., 8., 9., 7.])

In [60]:
condition = a < 3
a[condition]

array([1., 0., 2.])

### 2.2 Fancy Index
- numpy는 array를 index value로 사용해서 값 추출

In [64]:
a = np.array([2,4,6,8], float)
# 반드시 integer로 선언
b = np.array([0,0,1,3,2,1], int)
# bracket index, b배열의 값을 index로 하여 a의 값들을 추출함
a[b]

array([2., 2., 4., 8., 6., 4.])

In [65]:
# take 함수 : bracket index와 같은 효과
a.take(b)

array([2., 2., 4., 8., 6., 4.])

- matrix 형태의 data도 가능

In [66]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
# b를 Row index, c를 column index로 변환하여 표시
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

# 3. numpy data i/0
### 3.1 loadtxt & savetxt
- text type의 data를 읽고 저장하는 기능

3.1.1 파일호출

In [ ]:
a = np.loadtxt("./populations.txt")
a[:10] 

3.1.2 Int type 변환

In [ ]:
a_int = a.astype(int)
a_int[:3]

3.1.3 int_data.csv로 저장 <br>
fmt = "%.2"  => 소수점 2자리 까지 포함 <br>
저장기준 -> 탭 : \t <br> 
콤마 : , 

In [ ]:
# (파일명, 저장하고 싶은 array, 데이터 저장 기준)
np.savetxt("int_data.csv", a_int, delimiter=",")

### 3.2 numpy object 
- npy파일로 저장 <br>
np.save("파일명", arr = 저장하고 싶은 거) <br>
- npy파일 불러오기 <br>
np.load(file = "파일명")