# 1. Array Operations
### 1.1 Operations b/t arrays
- numpy is array간의 기본적인 사칙 연산을 지원

In [2]:
import numpy as np

In [4]:
test_a = np.array([[1,2,3], [4,5,6]], float)

In [5]:
# Matrix + Matrix 연산
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
# Matrix - Matrix
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Matrix 내 elements들 간 같은 위치에 있는 value들끼리 연산
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### 1.2 `Element-wise operations`
- Array간 shape이 same할 때 일어나는 연산
- 같은 위치에 있는 값끼리 연산됨

In [8]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### 1.3 Dot product
- Matrix의 기본 연산, dot 함수 사용

In [10]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [12]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### 1.4 Transpose (전치행렬)
- transpose or T attribute 사용

In [14]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
# Matrix 간 곱셈
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

### 1.5 Broadcasting
- shape이 다른 배열 간 연산을 지원하는 기능

In [19]:
# Matrix + Scalar
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [20]:
# Matrix - scalar
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [24]:
# Matrix * scalar
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [25]:
# Matrix / scalar
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [26]:
# Matrix // scalar => 몫
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [28]:
# Matrix ** scalar => 제곱
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

- Scalar, Vector 외에도 vector, matrix간의 연산도 지원 <br>
=> Vector가 Column과 Row의 개수를 맞춰줌 (확장함)

In [29]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10) # 10부터 10단위로
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### 1.6 Numpy performance #1
- timeit : jupyter 환경에서 코드의 performance를 체크하는 함수

In [32]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

internation_max = 100000000

vector = list(range(internation_max))
scalar = 2

In [33]:
# for loop을 이용한 성능
%timeit sclar_vector_product(scalar, vector)

6.52 s ± 94.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
# list comprehension을 이용한 성능
%timeit [scalar * value for value in range(internation_max)]

5.66 s ± 60.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [35]:
# numpy를 이용한 성능
%timeit np.arange(internation_max) * scalar

159 ms ± 18.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 1.7 Numpy performance #2
- 일반적으로 속도는 <br>
for loop < list comprehension < numpy

- 100,000,000 번의 loop이 돌 때, 약 4배 이상의 성능 차이를 보임
- numpy is C로 구현되어 있어, 성능을 확보하는 대신 파이썬의 가장 큰 특징인 dynamic typing을 포기
- 대용량 계산에서는 가장 흔히 사용됨
- Concatenate 처럼 계산이 아닌 ,할당에서는 연산 속도의 이점이 X