In [1]:
import numpy as np

> def n_size_ndarray_creation(n, dtype=np.int):  
    X = None  
    return X

- 함수목적  
  n의 제곱수로 2 dimentional array를 생성하는 ndarray.
- Args  
  n: 생성하고자 하는 ndarray의 row와 column의 개수  
  dtype: 생성하려는 ndarray의 data type (np.int)
- Returns  
  row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [2]:
arr = np.arange(3**2).reshape(3,3)
type(arr)

numpy.ndarray

In [3]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange(n**2).reshape(n,n)
    return X

C:\Users\pknu\AppData\Local\Temp\ipykernel_19052\1717552700.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def n_size_ndarray_creation(n, dtype=np.int):


> Ex)

In [4]:
n_size_ndarray_creation(8, dtype = np.int)

C:\Users\pknu\AppData\Local\Temp\ipykernel_19052\1530733019.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  n_size_ndarray_creation(8, dtype = np.int)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

> def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):  
    X = None  
  return X

- 함수목적  
    shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.
- Args  
    shape: 생성할려는 ndarray의 shape
    type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨
    dtype: 생성하려는 ndarray의 data type (np.int)
- Returns  
    shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨

In [5]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    # type = 0 -> element = 0
    if type == 0 :
        X = np.zeros(shape, dtype)
    # type = 1 -> element = 1
    elif type == 1 :
        X = np.ones(shape, dtype)
    # type = 99 -> element = empty
    else :
        X = np.empty(shape, dtype)
        
    return X

C:\Users\pknu\AppData\Local\Temp\ipykernel_19052\600320639.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):


In [6]:
zero_or_one_or_empty_ndarray((2,2), type = 1)

array([[1, 1],
       [1, 1]])

In [7]:
zero_or_one_or_empty_ndarray((3,3), type = 99)

array([[   4128860,    6029375,    3801155],
       [   5570652,    6619251,    7536754],
       [-511246336,        480,          0]])

> def change_shape_of_ndarray(X, n_row):   
    return X

- 함수목적  
    입력된 ndarray X를 n_row의 값을 row의 개수로 지정한 matrix를 반환함.  
    이때 입력하는 X의 size는 2의 거듭제곱수로 전제함.  
    만약 n_row과 1일 때는 matrix가 아닌 vector로 반환함.  
- Args  
    X: 입력하는 ndarray
    n_row: 생성할려는 matrix의 row의 개수
- Returns  
    row의 개수가 n_row인 Matrix 또는 Vector
    n_row가 1이면 Vector 값으로 반환함

In [15]:
def change_shape_of_ndarray(X, n_row):
    # n_row : 생성하려는 matrix row의 개수
    # n_row가 1일 경우 Vector 값을 반환
    if n_row == 1:
        X = X.flatten()
    else :
        X = X.reshape(n_row, -1)
    return X

> EX )

In [16]:
X = np.ones((32,32), dtype=np.int)
X

C:\Users\pknu\AppData\Local\Temp\ipykernel_23496\816447811.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.ones((32,32), dtype=np.int)


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [18]:
change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

In [17]:
change_shape_of_ndarray(X, 512)

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

- 시행 착 오 ,,,,

In [3]:
def concat_ndarray(X_1, X_2, axis):
    
    n_1 = X_1.ndim #X_1의 차원
    n_2 = X_2.ndim #X_2의 차원
    
    # axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨.
    

    if axis == 0 : 
        if n_1 == n_2 and n_1 == 2 : # X_1, X_2의 차원이 2차원인 경우
            if X_1.shape[1] == X_2.shape[1]:  # X_1, X_2의 열이 동일 할 때 
                return np.concatenate((X_1,X_2), axis = axis)
            else: # X_1, X_2의 열이 동일 하지 않을 때
                return False
        elif n_1 == n_2 and n_1 == 1: # X_1, X_2의 차원이 1차원인 경우
            if X_1.size == X_2.size : # X_1, X_2의 열이 동일 할 때
                return np.concatenate((X_1,X_2), axis = axis)
            else : # X_1, X_2의 열이 동일 하지 않을 때
                return False

        # X_1,X_2 Matrix, Vector 형태로 들어왔다면 Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인
        else : # X_1, X_2의 차원이 다른 경우
            if n_1 == 1 :
                if X_1.size == X_2.shape[1] :
                    X_1 = X_1[np.newaxis, :]
                    return np.concatenate((X_1,X_2), axis = axis)
                else :
                    return False
            elif n_2 == 1:
                if X_1.shape[1] == X_2.size :
                    X_2 = X_2[np.newaxis, :]
                    return np.concatenate((X_1,X_2), axis = axis)
                else :
                    return False


    else : # axis = 1인 경우
        if n_1 == n_2 and n_1 == 2 : # X_1, X_2의 차원이 2차원인 경우
            if X_1.shape[0] == X_2.shape[0]: # X_1, X_2의 행이 동일 할 때 
                return np.concatenate((X_1,X_2), axis = axis)
            else :
                return False
        elif n_1 == n_2 and n_1 == 1:
            X_1 = X_1[np.newaxis, :] # X_1 현재 1차원 -> 2차원
            X_2 = X_2[np.newaxis, :] # X_2 현재 1차원 -> 2차원
            return np.concatenate((X_1,X_2), axis = axis)

        # X_1,X_2 Matrix, Vector 형태로 들어왔다면 Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인
        else : # X_1, X_2의 차원이 다른 경우
            if n_1 == 1 :
                if X_1.size == X_2.shape[0] : #X_1의 열과 X_2의 행 비교
                    X_1 = X_1[np.newaxis, :]
                    return np.concatenate((X_1.T,X_2), axis = axis)
                else :
                    return False
            elif n_2 == 1:
                if X_1.shape[0] == X_2.size : #X_1의 행과 X_2의 열 비교
                    X_2 = X_2[np.newaxis, :]
                    return np.concatenate((X_1,X_2.T), axis = axis)
                else :
                    return False

- 찐

> def concat_ndarray(X_1, X_2, axis):  
    pass

- 함수목적  
    입력된 ndarray X_1과 X_2를 axis로 입력된 축을 기준으로 통합하여 반환하는 함수  
    X_1과 X_2는 matrix 또는 vector 임, 그러므로 vector 일 경우도 처리할 수 가 있어야 함  
    axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨.  
    단 X_1과 X_2 Matrix, Vector 형태로 들어왔다면, Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인할 것
- Args
    X_1: 입력하는 ndarray  
    X_2: 입력하는 ndarray  
    axis: 통합의 기준이 되는 축 0 또는 1임
- Returns
    X_1과 X_2과 통합된 matrix 타입의 ndarray

In [30]:
def concat_ndarray(X_1, X_2, axis):

    n_1 = X_1.ndim #X_1의 차원
    n_2 = X_2.ndim #X_2의 차원
    
    # axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨.
    # 1차원일 때 열의 개수 = X_1.size
    if axis == 0 : 
        # X_1, X_2의 차원이 2차원인 경우
        if n_1 == n_2 and n_1 == 2 : 
            if X_1.shape[1] == X_2.shape[1]:  # X_1, X_2의 열이 동일할 때 
                return np.vstack((X_1,X_2))
            else: # X_1, X_2의 열이 동일하지 않을 때
                return False

        # X_1, X_2의 차원이 1차원인 경우
        elif n_1 == n_2 and n_1 == 1: 
            if X_1.size == X_2.size : # X_1, X_2의 열이 동일할 때 
                return np.vstack((X_1,X_2))
            else:
                return False

        else:
            if n_1 == 1:
                if X_1.size == X_2.shape[1] :
                    return np.vstack((X_1,X_2))
                else:
                    return False
            else:
                if X_1.shape[1] == X_2.size :
                    return np.vstack((X_1,X_2))
                else:
                    return False
                    
    else : # axis = 1인 경우
        if n_1 == n_2 and n_1 == 2 : # X_1, X_2의 차원이 2차원인 경우
            if X_1.shape[0] == X_2.shape[0]:  # X_1, X_2의 행이 동일할 때 
                return np.hstack((X_1,X_2))
            else: # X_1, X_2의 행이 동일하지 않을 때
                return False
                
        elif n_1 == n_2 and n_1 == 1: # X_1, X_2의 차원이 1차원인 경우
            return np.hstack((X_1,X_2))
            
        else:
            return False
          

> EX )

In [31]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a, b, 1)

False

In [34]:
a = np.array([1, 2])
b = np.array([5, 6, 7])
concat_ndarray(a, b, 1)
#a.size, b.size

array([1, 2, 5, 6, 7])

In [199]:
a = np.array([1, 2])
b = np.array([5, 6, 7])
concat_ndarray(a, b, 0)

False

In [35]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
concat_ndarray(a, b, 1)

False

> def normalize_ndarray(X, axis=99, dtype=np.float32):  
    pass

- 함수목적
    입력된 Matrix 또는 Vector를 ndarray X의 정규화된 값으로 변환하여 반환함.  
    이때 정규화 변환 공식 Z = (X - X의평균) / X의 표준편차로 구성됨.  
    X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨.  
    Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함.  
    axis가 99일 경우 전체 값에 대한 normalize 값을 구함.  
- Args
    X: 입력하는 ndarray,
    axis: normalize를 구하는 기준이 되는 축으로 0, 1 또는 99임, 단 99는 axis 구분 없이 전체값으로 평균과 표준편차를 구함.  
    dtype: data type으로 np.float32로 구성  
- Returns
    정규화된 ndarra

In [263]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    #X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨.

    #Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함.
    if axis == 0:
        X_m = np.mean(X, axis = axis)
        X_s = np.std(X, axis = axis)
        z = (X - X_m) / X_s
        return z

    elif axis == 1:
        X_m = np.mean(X, axis = axis)
        X_s = np.std(X, axis = axis)
        X_m = X_m[np.newaxis, :].T
        X_s = X_s[np.newaxis, :].T
        z = (X - X_m)/X_s
        return z

    #axis가 99일 경우 전체 값에 대한 normalize 값을 구함.
    else:
        z = (X - np.mean(X)) / np.std(X)
        return z

> EX )

In [264]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [265]:
normalize_ndarray(X)

array([[-1.593255  , -1.3035723 ],
       [-1.0138896 , -0.7242068 ],
       [-0.4345241 , -0.14484136],
       [ 0.14484136,  0.4345241 ],
       [ 0.7242068 ,  1.0138896 ],
       [ 1.3035723 ,  1.593255  ]], dtype=float32)

In [266]:
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [267]:
normalize_ndarray(X, 0)

array([[-1.46385, -1.46385],
       [-0.87831, -0.87831],
       [-0.29277, -0.29277],
       [ 0.29277,  0.29277],
       [ 0.87831,  0.87831],
       [ 1.46385,  1.46385]], dtype=float32)

> def save_ndarray(X, filename="test.npy"):  
  pass

- 함수목적  
    입력된 ndarray X를 argument filename으로 저장함
- Args  
    X: 입력하는 ndarray
    filename: 저장할려는 파일이름

In [271]:
def save_ndarray(X, filename="test.npy"):
    np.save(filename, arr = X)

In [274]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(X, filename)

In [275]:
np.load(file = "test.npy")

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]], dtype=float32)

> def boolean_index(X, condition):  
  pass

- 함수목적  
    입력된 ndarray X를 String type의 condition 정보를 바탕으로 해당 컨디션에 해당하는 ndarray X의 index 번호를 반환함  
    단 이때, str type의 조건인 condition을 코드로 변환하기 위해서는 eval(str("X") + condition)를 사용할 수 있음
- Args  
    X: 입력하는 ndarray  
    condition: string type의 조건 (">3", "== 5", "< 15")
- Returns  
조건에 만족하는 ndarray X의 index

In [2]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

> Ex )

In [3]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
X 

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]], dtype=float32)

In [4]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
boolean_index(X, "== 3")

(array([0], dtype=int64), array([3], dtype=int64))

In [100]:
X = np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

> def find_nearest_value(X, target_value):  
    pass

- 함수목적  
    입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함  
    이때 X를 list로 변경하여 처리하는 것은 실패로 간주함.
- Args  
    X: 입력하는 vector type의 ndarray  
    target_value : 가장 유사한 값의 기준값이 되는 값  
- Returns  
    target_value와 가장 유사한 값

In [109]:
def find_nearest_value(X, target_value):
    X_t = np.abs(X - target_value)
    i = np.argmin(X_t)
    return X[i]

In [110]:
X = np.random.uniform(0, 1, 100)
target_value = 0.3
find_nearest_value(X, target_value)

0.29734016895679793

> def get_n_largest_values(X, n):  
    pass

- 함수목적  
    입력된 vector type의 ndarray X에서 큰 숫자 순서대로 n개의 값을 반환함.
- Args  
    X: vector type의 ndarray  
    n: 반환할려는 element의 개수
- Returns  
ndarray X의 element중 큰 숫자 순서대로 n개 값이 반환됨 ndarray

In [125]:
def get_n_largest_values(X, n):
    large_X = X[X.argsort()[::-1][:n]]
    return large_X

> EX )

In [126]:
X = np.array([1,3,5,7,9])
get_n_largest_values(X,2)

array([9, 7])

In [127]:
X = np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)

array([0.99282476, 0.97613982, 0.97290802])